# Generated by Django 3.2.3 on 2021-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attend_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='언제부터 방문하실 계획이신가요?'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attend_yn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='참석 여부'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='junior_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2세 이름'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='offline_camera_yn',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='아날로그 사진기 수령 여부'),
        ),
        migrations.AddField(
            model_name='letter',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='letter',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='풀네임'),
        ),
        migrations.AddField(
            model_name='letter',
            name='honor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='직함'),
        ),
        migrations.AddField(
            model_name='letter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='letter',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='cheering',
            name='cheer_message',
            field=models.TextField(blank=True, null=True, verbose_name='응원 메세지'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='rwhqy', max_length=50, unique=True, verbose_name='unique code'),
        ),
    ]
