# Generated by Django 3.2.3 on 2021-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20210604_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='zxnsf', max_length=50, unique=True, verbose_name='unique code'),
        ),
    ]
