# Generated by Django 3.2.3 on 2021-06-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_auto_20210604_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='invitee',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='inviter',
            new_name='invitee',
        ),
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='cmvji', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='unique code'),
        ),
    ]
