# Generated by Django 3.2.3 on 2021-06-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_auto_20210605_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='qznbe', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='unique code'),
        ),
    ]
