# Generated by Django 3.2.3 on 2021-06-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_auto_20210606_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='cheering',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='zekzz', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='unique code'),
        ),
    ]
