# Generated by Django 3.2.3 on 2021-06-06 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_auto_20210606_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 3, 52, 3, 715036), verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='cheering',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 3, 52, 3, 715502), verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 3, 52, 3, 716059), verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='ykxcg', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='unique code'),
        ),
    ]
